package com.jlab.mybatis.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @return the value of PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @param name the value for PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}