package com.jlab.persistence.mybatis.model;

import java.util.Date;

public class CustomerOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER_ORDER.ID
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER_ORDER.DATE
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER_ORDER.CUSTOMER_ID
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER_ORDER.ID
     *
     * @return the value of PUBLIC.CUSTOMER_ORDER.ID
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER_ORDER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER_ORDER.ID
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER_ORDER.DATE
     *
     * @return the value of PUBLIC.CUSTOMER_ORDER.DATE
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER_ORDER.DATE
     *
     * @param date the value for PUBLIC.CUSTOMER_ORDER.DATE
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER_ORDER.CUSTOMER_ID
     *
     * @return the value of PUBLIC.CUSTOMER_ORDER.CUSTOMER_ID
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER_ORDER.CUSTOMER_ID
     *
     * @param customerId the value for PUBLIC.CUSTOMER_ORDER.CUSTOMER_ID
     *
     * @mbg.generated Tue Apr 10 01:22:40 EEST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}