package com.jlab.mybatis.model;

public class OrderProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDER_PRODUCT.PRODCUT_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    private Integer prodcutId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDER_PRODUCT.QUANTITY
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @return the value of PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @param orderId the value for PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDER_PRODUCT.PRODCUT_ID
     *
     * @return the value of PUBLIC.ORDER_PRODUCT.PRODCUT_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public Integer getProdcutId() {
        return prodcutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDER_PRODUCT.PRODCUT_ID
     *
     * @param prodcutId the value for PUBLIC.ORDER_PRODUCT.PRODCUT_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public void setProdcutId(Integer prodcutId) {
        this.prodcutId = prodcutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDER_PRODUCT.QUANTITY
     *
     * @return the value of PUBLIC.ORDER_PRODUCT.QUANTITY
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDER_PRODUCT.QUANTITY
     *
     * @param quantity the value for PUBLIC.ORDER_PRODUCT.QUANTITY
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}