package com.jlab.mybatis.model;

public class OrderProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Tue Apr 10 01:40:21 EEST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 10 01:40:21 EEST 2018
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @return the value of PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Tue Apr 10 01:40:21 EEST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @param orderId the value for PUBLIC.ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Tue Apr 10 01:40:21 EEST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDER_PRODUCT.PRODUCT_ID
     *
     * @return the value of PUBLIC.ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 10 01:40:21 EEST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDER_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for PUBLIC.ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 10 01:40:21 EEST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}