package com.jlab.mybatis.model;

import java.util.Date;
import java.util.List;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PORDER.ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PORDER.DATE
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PORDER.CUSTOMER_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PORDER.ID
     *
     * @return the value of PUBLIC.PORDER.ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PORDER.ID
     *
     * @param id the value for PUBLIC.PORDER.ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PORDER.DATE
     *
     * @return the value of PUBLIC.PORDER.DATE
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PORDER.DATE
     *
     * @param date the value for PUBLIC.PORDER.DATE
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PORDER.CUSTOMER_ID
     *
     * @return the value of PUBLIC.PORDER.CUSTOMER_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PORDER.CUSTOMER_ID
     *
     * @param customerId the value for PUBLIC.PORDER.CUSTOMER_ID
     *
     * @mbg.generated Mon Apr 23 18:03:59 EEST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    private Customer customer;
    private List<Product> products;
}