package com.jlab.mybatis.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.COST
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    private String cost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.ID
     *
     * @return the value of PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.ID
     *
     * @param id the value for PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.COST
     *
     * @return the value of PUBLIC.PRODUCT.COST
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    public String getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.COST
     *
     * @param cost the value for PUBLIC.PRODUCT.COST
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    public void setCost(String cost) {
        this.cost = cost;
    }
}