package com.jlab.mybatis.dao;

import com.jlab.mybatis.model.CustomerOrder;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CustomerOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMER_ORDER
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMER_ORDER
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    int insert(CustomerOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMER_ORDER
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    CustomerOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMER_ORDER
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    List<CustomerOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMER_ORDER
     *
     * @mbg.generated Tue Apr 10 01:25:52 EEST 2018
     */
    int updateByPrimaryKey(CustomerOrder record);
}